name: bitsdojo_window
description: A package to help with creating custom windows with Flutter desktop (custom border, titlebar and minimize/maximize/close buttons) and common desktop window operations (show/hide/position on screen) for Windows and macOS
version: 0.2.0
homepage: https://www.bitsdojo.com
repository: https://github.com/bitsdojo/bitsdojo_window
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      windows:
        default_package: bitsdojo_window_windows
      macos:
        default_package: bitsdojo_window_macos
      linux:
        default_package: bitsdojo_window_linux

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window_platform_interface:
    # git:
    #   url: https://github.com/totallabltd/bitsdojo_window.git
    #   ref: master
    #   path: bitsdojo_window_platform_interface
    path: ../bitsdojo_window_platform_interface
  bitsdojo_window_windows:
    # git:
    #   url: https://github.com/totallabltd/bitsdojo_window.git
    #   ref: master
    #   path: bitsdojo_window_windows
    path: ../bitsdojo_window_windows
  bitsdojo_window_macos:
    # git:
    #   url: https://github.com/totallabltd/bitsdojo_window.git
    #   ref: master
    #   path: bitsdojo_window_macos
    path: ../bitsdojo_window_macos
  bitsdojo_window_linux:
    # git:
    #   url: https://github.com/totallabltd/bitsdojo_window.git
    #   ref: master
    #   path: bitsdojo_window_linux
    path: ../bitsdojo_window_linux
